// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => const FirebaseOptions(
        apiKey: 'AIzaSyCAzSbzrxt-kA7YSWLg-qaaT8v8dix_NKE',
        appId: '1:519731202341:web:b8df28c1231eed64c7b2cc',
        messagingSenderId: '519731202341',
        projectId: 'voltconnect-30c9b',
        authDomain: 'voltconnect-30c9b.firebaseapp.com',
        storageBucket: 'voltconnect-30c9b.firebasestorage.app',
        measurementId: 'G-D6TJ7N9W3V',
      );

  static FirebaseOptions get android => const FirebaseOptions(
        apiKey: 'AIzaSyCAzSbzrxt-kA7YSWLg-qaaT8v8dix_NKE',
        appId: '1:519731202341:android:a05f35d3c4c0295dc7b2cc',
        messagingSenderId: '519731202341',
        projectId: 'voltconnect-30c9b',
        storageBucket: 'voltconnect-30c9b.firebasestorage.app',
      );

  static FirebaseOptions get ios => const FirebaseOptions(
        apiKey: 'AIzaSyCAzSbzrxt-kA7YSWLg-qaaT8v8dix_NKE',
        appId: '1:519731202341:ios:a05f35d3c4c0295dc7b2cc', // Note: Guessed from pattern, the .env had PLACEHOLDER
        messagingSenderId: '519731202341',
        projectId: 'voltconnect-30c9b',
        storageBucket: 'voltconnect-30c9b.firebasestorage.app',
        iosBundleId: 'com.voltconnect',
      );
}
